import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import React from 'react';
// import footer from './ui/footer';
import {NextUIProvider} from "@nextui-org/react";

export function Footer() {  
  return <footer>Footer content</footer>;
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen`}
      >
        <NextUIProvider className="h-full">
          {children}
        </NextUIProvider>
      </body>
    </html>
  );
}
