import type { Metadata } from "next";
import "./globals.css";
import Footer from './Footer';
import React, { ReactNode } from 'react';

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <head>
        <title>Handcrafted Haven</title>
      </head>
      <body>{children}</body>
      <Footer />
    </html>
  );
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



